name: text_validator
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/Fahaddada47/text_validator
repository: https://github.com/Fahaddada47/text_validator

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

topics:
  - formvalidation

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

flutter:
  uses-material-design: true